### PR TITLE
Change to "Waiting for Window"

### PR DESCRIPTION
**Pull request by CrystalBallBe**
Fixed typo (reference: https://github.com/AugurProject/whitepaper/pull/66#discussion_r470392438).
Changed `Waiting for Next Fee Window to Begin` to `Waiting for Window` in the flowchart.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Can you paste a screenshot of what the new image looks like?  It doesn't render in GitHub.

**Comment by CrystalBallBe** [comment]
Can you see it from here?

unknown

**Comment by MicahZoltu** [comment]
Sorry, I meant v2/english/new_reporting.xml, which I assumed was an encoded image of some kind?

**Comment by CrystalBallBe** [comment]
@MicahZoltu I changed the text of the flowchart in the following way, then I got the 
 new `new_reporting.xml` and `new_reporting.png`. 
(But I haven't confirmed it with anyone, so I'm not sure if this is correct. Are the steps below correct? @Austin-Williams)
1. Open the site www.draw.io.  (The reason I did it was because the xml contained the string `www.draw.io`.)

1. Import the `new_reporting.xml` at that site.  Then the flowchart is drawn.  (So ​​I believe this xml is the source for that flowchart.)

1. Change the text and save.

1. Export as PNG file.

1. Export as XML file.

If you import the XML in a similar way and the flowchart is rendered correctly, I think you can judge that the XML is correct (at least available as a source for the flowchart).

**Comment by MicahZoltu** [comment]
Ah, the XML file is the original (for editing) and the PNG is the file included in the paper.  Got it!

**Pull request merged**
