### PR TITLE
Update augur-whitepaper-v2.pdf

### PR DESCRIPTION
**Pull request by CrystalBallBe**
I have updated the material files (e.g. `main.tex`) for the PDF `augur-whitepaper-v2.pdf`, but I have not updated the PDF file itself.
I believe the whitepaper is not complete yet. However I will not update the material files for a while, so I created this PDF file from the latest material files at the moment.
(I should have updated this PDF file whenever I submitted a pull request for materials files, sorry. )

This PDF file was generated on [Overleaf](https://www.overleaf.com/read/jtqxvyktydxx).

### CODE REVIEW

**Comment by MicahZoltu** [comment]
@tomkysar Do we have a process for generating the whitepaper from the various files it is derived from?  I previously assumed there was some CI process that did it, but this PR suggests otherwise.  I very briefly scanned the document and can at least assert that @CrystalBallBe didn't draw pictures of penises all over it or anything, but I didn't do a complete and thorough audit to make sure it doesn't have something sneaky hidden among all of the words.

FWIW: @CrystalBallBe has been the sole editor of the whitepaper for a while now, submitting a lot of minor tweaks and adjustments, so this isn't like some total stranger showing up and asking us to replace the PDF with one of their own.

**Comment by CrystalBallBe** [comment]
@MicahZoltu @tomkysar I believe I didn't draw pictures of penises in the whitepaper. But while I was making this file, I thought about a penis few times (actually I went to a bathroom at that time), so I might have drawn it unconsciously. Therefore a thorough audit of this file is necessary.

...seriously, If someone updates the PDF file, that's fine. Then I don't mind if this pull request is closed without being merged. I just want to keep the PDF file up-to-date.

**Comment by tinybike** [comment]
@CrystalBallBe @MicahZoltu The v1 whitepaper was also just generated on Overleaf!  I don't think this repo was ever set up to generate the PDF from the source files automatically though.  Maybe there's a way to configure Travis CI to do that...?

**Comment by tinybike** [comment]
@CrystalBallBe For simplicity, I'm going to close this PR since I just submitted another PR https://github.com/AugurProject/whitepaper/pull/76 which has a recompiled PDF that includes all previous changes.

**Pull request closed without merging**
